### ISSUE TITLE
Jenkins fails with OutOfMemoryError while uploading FPR to SSC

### ISSUE THREAD

**Issue by AbirDas** [jenkinsci/fortify-plugin#24]
I am getting below error, when am trying to upload fortify .fpr file to ssc:- https://fortifyssc.*******.com from Jenkins build configuration.

serverjava.lang.OutOfMemoryError: Java heap space

System where Jenkins is installed RAM size 32GB. and the project report am trying to upload to SSC is a simple project as per document it required 16GM RAM, and the project is simple ANT build.

Not sure what need to be done further to fix this, is there any setting in Jenkins i can specify RAM & CPU size?

What i got from google is Jenkins will take by default available space. Please find attached screenshot of log, and system configuration.

<img width="665" alt="IssueWithJenkins" src="https://user-images.githubusercontent.com/4902446/92215233-1872fd80-eeb2-11ea-8a9c-9af872585f13.png">

Any suggestion is appreciated, 

Thanks & Regards.
Abir Das.

**Comment by akaryakina** [comment]
How did you deploy and run the Jenkins server itself? I don't think that this issue is specific to our plugin, I believe it's just a general lack of memory allocated for your web server that runs Jenkins. If you simply run Jenkins with a war and the supplied Jetty server, then the java -jar jenkins.war can be turned into java -Xms4G -Xmx16G jenkins.war. But otherwise, it will depend on your app server, platform and the deployment type. The first search result showed me this article for one of the options: https://stackoverflow.com/questions/14762162/how-do-i-give-jenkins-more-heap-space-when-its-running-as-a-daemon-on-ubuntu

**Comment by AbirDas** [comment]
Thanks for suggestion, i agree this looks like Jenkins issue and not Fortify. just raised this issue to get any suggestion or workaround. as my build server is in windows machine so used this options: https://stackoverflow.com/questions/17369522/set-default-heap-size-in-windows

But getting same error.

**Comment by AbirDas** [comment]
Issue was indeed in Jenkins side after updating argument issue got resolved. 
https://stackoverflow.com/questions/5936519/how-to-give-jenkins-more-heap-space-when-it%C2%B4s-started-as-a-service-under-windows
thanks.
