### ISSUE TITLE
Fortify Assessment plugin is not populating data to Octane

### ISSUE THREAD

**Issue by msteffensen19** [jenkinsci/fortify-plugin#3]
The current version (19.1.29) is not populating vulnerabilities into Octane. This was also not working in version 18.20 but version 17.10 did have it working.

**Comment by akaryakina** [comment]
Hi, thank you for reporting the issue. However, it looks like the issue is not related to our plugin, but to the implementation of the Octane plugin https://github.com/jenkinsci/hpe-application-automation-tools-plugin. Let's file it there.
Note, we significantly reworked the plugin for 19.1 and open sourced it, so any other tools that were relying on plugin internals would not work. It's up to the octane team to write a new integration now. The previous versions were not open sourced, so they were not supposed to have any integration written for, especially using reflection like the current integration does.
